### ISSUE TITLE
Quick question about Qt if you don't mind, from a new user trying to get the hang of it (using your project as a reference to learn)

### ISSUE THREAD

**Issue by MostHated** [ShaneWilliamson/golang-chat#5]
Hey there,
    I am just learning Qt, I started yesterday, so I have been going around looking at projects using it, trying to get the hang of it. I noticed you had the moc.go file in there, is that something you had to add? I noticed some projects have it in the repo, some don't, but without it and everything that is in it, GoLand throws a serious number of errors for unresolved references.  

Example is, in your clientUI.go in the tcpClient package, lines 215 and 216, you have:

```Go
	model.GetUIInstance().ClientQTInstance = model.NewClientQT(nil)
	model.GetUIInstance().ClientQTInstance.ConnectReloadUI(func() { ReloadUI(client) })
```
The ```model.NewClientQT(nil)``` ends up being something in that moc.go. Without it though, of course, that part becomes an unresolved reference. I am just wondering if you had to develop the application with those references being unresolved and then that file is generated after the fact, or how does that work exactly?

Thanks!
-MH

**Comment by ShaneWilliamson** [comment]
Hi @MostHated 
Apologies on the long delay. While I'm guessing you've either found an answer by this point or have moved on to other endeavors, I'll still try to give you an answer here.

My memory of developing this application is a little fuzzy, it's been a while, but it appears that I had vendored the moc files ahead of time, I recall using QT and golang to be quite troublesome as I was new to using both the language and framework, so I wouldn't necessarily recommend vendoring them in in such a fashion. Hopefully you had a better experience with QT than I!

**Comment by MostHated** [comment]
They there. Better late than never, as they say, lol. No worries. I actually ended up using Go/Flutter for my application. I appreciate you getting back to me though!

Thanks,
-MH

**Comment by ShaneWilliamson** [comment]
Very true! I'm glad to hear everything worked out.
